import type { ComponentType } from 'react'
import type { InputType } from 'storybook/internal/types'
import type { BlockControlsManifest, FieldControl } from './manifest'
import manifest from './manifest.generated.json'

/**
 * Storybook controls for a CMS block, from the block's own Payload config
 * (`./manifest.ts`, generated by `pnpm generate:block-controls`). A story
 * spreads the result into its meta: `argTypes` gives every select, radio,
 * checkbox and text field the editor's options, labels, descriptions,
 * Design grouping and show/hide rules; `args` seeds the editor's defaults so
 * a story starts where a fresh block does. Content fields (rich text, media,
 * rows) stay with the story's fixtures.
 */
export type BlockSlug = keyof typeof manifest

type PropsOf<C> = C extends ComponentType<infer P> ? P : never

const blocks = manifest as unknown as BlockControlsManifest

/** Payload's row identity: never a control. */
const ROW_KEYS = ['id', 'blockName', 'blockType'] as const

const CONTENT_CATEGORY = 'Content'

const inputType = (field: FieldControl): InputType => {
  const base: InputType = {
    name: field.label,
    description: field.description,
    if: field.if,
    table: { category: field.group ?? CONTENT_CATEGORY },
  }
  switch (field.control) {
    case 'select':
    case 'radio': {
      const labels = Object.fromEntries(field.options.map(({ label, value }) => [value, label]))
      return {
        ...base,
        control: { type: field.control === 'radio' ? 'inline-radio' : 'select', labels },
        options: field.options.map(({ value }) => value),
        table: {
          ...base.table,
          defaultValue:
            field.defaultValue === undefined ? undefined : { summary: labels[field.defaultValue] },
        },
      }
    }
    case 'boolean':
      return {
        ...base,
        control: 'boolean',
        table: {
          ...base.table,
          defaultValue:
            field.defaultValue === undefined ? undefined : { summary: String(field.defaultValue) },
        },
      }
    case 'text':
      return { ...base, control: 'text' }
    case 'none':
      return { ...base, control: false }
  }
}

export const blockControls = <C>(
  slug: BlockSlug,
): {
  args: Partial<PropsOf<C>>
  argTypes: Partial<Record<keyof PropsOf<C>, InputType>>
} => {
  const { fields } = blocks[slug]
  const argTypes = Object.fromEntries([
    ...fields.map((field) => [field.name, inputType(field)]),
    ...ROW_KEYS.map((key) => [key, { table: { disable: true } }]),
  ]) as Partial<Record<keyof PropsOf<C>, InputType>>
  const args = Object.fromEntries(
    fields.flatMap((field) =>
      'defaultValue' in field && field.defaultValue !== undefined
        ? [[field.name, field.defaultValue]]
        : [],
    ),
  ) as Partial<PropsOf<C>>
  return { args, argTypes }
}
