import { getMediaUrl } from '@/utilities/getMediaURL'
import { type Effect, lookPosterSrc } from '../studio/effect'
import { EFFECTS } from '../studio/effects'
import type { EffectVisual, PosterMediaSource } from './descriptor'

/**
 * Code-owned preset stills. One per look and polarity, rendered with alpha so
 * the CSS ground beneath (a Section band, the hero's `bg-background`) owns the
 * color and the still matches the live field's composite. They represent the
 * look, not any one entry's seed; an approved `posterMedia` upload replaces
 * them when an editor needs specific artwork for a shipped look.
 *
 * Files live in `public/images/<effect's posterDirectory>/<look>-<surface>.webp`
 * at `STREAK_POSTER_SIZE`, regenerated by `scripts/visual-posters.ts`. The
 * revision query keys the optimizer cache to the effect's look revision. An
 * effect that draws an opaque frame (`Effect.blend`) ships opaque stills, and
 * the slot composites them the way it composites the canvas.
 */
export const STREAK_POSTER_SIZE = { width: 1600, height: 900 } as const

type StreakPosterSurface = 'dark' | 'light'

/** MIME the menu and social fallbacks report for a preset poster. */
const STREAK_POSTER_MIME = 'image/webp'

export type PosterImage = {
  src: string
  width: number
  height: number
  mime: string
  alt: string
}

/**
 * The URL for a poster upload, through the path images use here: the
 * Cloudflare Images delivery URL when the media has synced, else the stored file.
 */
const mediaPosterImage = (media: PosterMediaSource): PosterImage | null => {
  const src =
    (media as { cloudflareImageUrl?: string | null }).cloudflareImageUrl ||
    getMediaUrl(media.url, media.updatedAt)
  if (!src) return null
  return {
    src,
    width: media.width ?? STREAK_POSTER_SIZE.width,
    height: media.height ?? STREAK_POSTER_SIZE.height,
    mime: media.mimeType ?? 'image/*',
    alt: '',
  }
}

const presetPosterImage = (
  effect: Effect,
  look: string,
  surface: StreakPosterSurface,
): PosterImage => ({
  src: lookPosterSrc(effect, look, surface),
  width: STREAK_POSTER_SIZE.width,
  height: STREAK_POSTER_SIZE.height,
  mime: STREAK_POSTER_MIME,
  alt: '',
})

export type VisualPosters = { light: PosterImage; dark: PosterImage; single: boolean }

/**
 * One poster resolver serves page slots, cards and takeover-menu previews, for
 * every effect: a published Studio look's rendered pair, then the editor's
 * upload, then the shipped look's stills. The Studio pair wins over an upload
 * because it is one still per ground, rendered from the numbers the slot runs;
 * one upload can only serve both grounds alike.
 */
export function visualPosters({ kind, descriptor }: EffectVisual): VisualPosters {
  const posters = descriptor.release?.posters
  const light = posters && mediaPosterImage(posters.light)
  const dark = posters && mediaPosterImage(posters.dark)
  if (light && dark) return { light, dark, single: false }
  const upload = descriptor.posterMedia ? mediaPosterImage(descriptor.posterMedia) : null
  if (upload) return { light: upload, dark: upload, single: true }
  return {
    light: presetPosterImage(EFFECTS[kind], descriptor.look, 'light'),
    dark: presetPosterImage(EFFECTS[kind], descriptor.look, 'dark'),
    single: false,
  }
}
