import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_content_columns_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_pages_blocks_content_container_width" AS ENUM('contained', 'fullWidth');
  CREATE TYPE "public"."enum_pages_blocks_media_block_aspect_ratio" AS ENUM('landscape', 'square', 'portrait', 'original');
  CREATE TYPE "public"."enum_pages_blocks_media_block_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_pages_blocks_media_block_space_pt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_media_block_space_pb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_media_block_space_mt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_media_block_space_mb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_pages_blocks_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__pages_v_blocks_content_container_width" AS ENUM('contained', 'fullWidth');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_aspect_ratio" AS ENUM('landscape', 'square', 'portrait', 'original');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_space_pt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_space_pb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_space_mt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_space_mb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__pages_v_blocks_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_works_blocks_content_columns_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_works_blocks_content_container_width" AS ENUM('contained', 'fullWidth');
  CREATE TYPE "public"."enum_works_blocks_media_block_aspect_ratio" AS ENUM('landscape', 'square', 'portrait', 'original');
  CREATE TYPE "public"."enum_works_blocks_media_block_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_works_blocks_media_block_space_pt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_works_blocks_media_block_space_pb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_works_blocks_media_block_space_mt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_works_blocks_media_block_space_mb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum_works_blocks_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_works_blocks_tabs_tabs_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum_works_blocks_tabs_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__works_v_blocks_content_columns_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__works_v_blocks_content_container_width" AS ENUM('contained', 'fullWidth');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_aspect_ratio" AS ENUM('landscape', 'square', 'portrait', 'original');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_space_pt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_space_pb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_space_mt" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__works_v_blocks_media_block_space_mb" AS ENUM('none', 'sm', 'md', 'lg', 'xl');
  CREATE TYPE "public"."enum__works_v_blocks_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__works_v_blocks_tabs_tabs_slider_theme" AS ENUM('system', 'light', 'dark');
  CREATE TYPE "public"."enum__works_v_blocks_tabs_theme" AS ENUM('system', 'light', 'dark');
  ALTER TYPE "public"."enum_pages_blocks_content_theme" ADD VALUE 'system' BEFORE 'light';
  ALTER TYPE "public"."enum_pages_hero_type" ADD VALUE 'home' BEFORE 'highImpact';
  ALTER TYPE "public"."enum__pages_v_blocks_content_theme" ADD VALUE 'system' BEFORE 'light';
  ALTER TYPE "public"."enum__pages_v_version_hero_type" ADD VALUE 'home' BEFORE 'highImpact';
  ALTER TYPE "public"."enum_works_blocks_content_theme" ADD VALUE 'system' BEFORE 'light';
  ALTER TYPE "public"."enum_works_hero_type" ADD VALUE 'home' BEFORE 'highImpact';
  ALTER TYPE "public"."enum__works_v_blocks_content_theme" ADD VALUE 'system' BEFORE 'light';
  ALTER TYPE "public"."enum__works_v_version_hero_type" ADD VALUE 'home' BEFORE 'highImpact';
  ALTER TABLE "pages_blocks_content_columns" RENAME COLUMN "section_heading_heading" TO "section_heading_eyebrow";
  ALTER TABLE "_pages_v_blocks_content_columns" RENAME COLUMN "section_heading_heading" TO "section_heading_eyebrow";
  ALTER TABLE "works_blocks_content_columns" RENAME COLUMN "section_heading_heading" TO "section_heading_eyebrow";
  ALTER TABLE "pages_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'system';
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'system';
  ALTER TABLE "works_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'system';
  ALTER TABLE "_works_v_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'system';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "section_heading_content" jsonb;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "slider_theme" "enum_pages_blocks_content_columns_slider_theme" DEFAULT 'system';
  ALTER TABLE "pages_blocks_content" ADD COLUMN "container_width" "enum_pages_blocks_content_container_width" DEFAULT 'contained';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "aspect_ratio" "enum_pages_blocks_media_block_aspect_ratio" DEFAULT 'landscape';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "theme" "enum_pages_blocks_media_block_theme" DEFAULT 'system';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "space_pt" "enum_pages_blocks_media_block_space_pt" DEFAULT 'md';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "space_pb" "enum_pages_blocks_media_block_space_pb" DEFAULT 'md';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "space_mt" "enum_pages_blocks_media_block_space_mt" DEFAULT 'none';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "space_mb" "enum_pages_blocks_media_block_space_mb" DEFAULT 'none';
  ALTER TABLE "pages_blocks_slider" ADD COLUMN "theme" "enum_pages_blocks_slider_theme" DEFAULT 'system';
  ALTER TABLE "pages" ADD COLUMN "hero_show_content" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "section_heading_content" jsonb;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "slider_theme" "enum__pages_v_blocks_content_columns_slider_theme" DEFAULT 'system';
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "container_width" "enum__pages_v_blocks_content_container_width" DEFAULT 'contained';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "aspect_ratio" "enum__pages_v_blocks_media_block_aspect_ratio" DEFAULT 'landscape';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "theme" "enum__pages_v_blocks_media_block_theme" DEFAULT 'system';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "space_pt" "enum__pages_v_blocks_media_block_space_pt" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "space_pb" "enum__pages_v_blocks_media_block_space_pb" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "space_mt" "enum__pages_v_blocks_media_block_space_mt" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "space_mb" "enum__pages_v_blocks_media_block_space_mb" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_slider" ADD COLUMN "theme" "enum__pages_v_blocks_slider_theme" DEFAULT 'system';
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_show_content" boolean DEFAULT true;
  ALTER TABLE "works_blocks_content_columns" ADD COLUMN "section_heading_content" jsonb;
  ALTER TABLE "works_blocks_content_columns" ADD COLUMN "slider_theme" "enum_works_blocks_content_columns_slider_theme" DEFAULT 'system';
  ALTER TABLE "works_blocks_content" ADD COLUMN "container_width" "enum_works_blocks_content_container_width" DEFAULT 'contained';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "aspect_ratio" "enum_works_blocks_media_block_aspect_ratio" DEFAULT 'landscape';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "theme" "enum_works_blocks_media_block_theme" DEFAULT 'system';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "space_pt" "enum_works_blocks_media_block_space_pt" DEFAULT 'md';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "space_pb" "enum_works_blocks_media_block_space_pb" DEFAULT 'md';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "space_mt" "enum_works_blocks_media_block_space_mt" DEFAULT 'none';
  ALTER TABLE "works_blocks_media_block" ADD COLUMN "space_mb" "enum_works_blocks_media_block_space_mb" DEFAULT 'none';
  ALTER TABLE "works_blocks_slider" ADD COLUMN "theme" "enum_works_blocks_slider_theme" DEFAULT 'system';
  ALTER TABLE "works_blocks_tabs_tabs" ADD COLUMN "slider_theme" "enum_works_blocks_tabs_tabs_slider_theme" DEFAULT 'system';
  ALTER TABLE "works_blocks_tabs" ADD COLUMN "theme" "enum_works_blocks_tabs_theme" DEFAULT 'system';
  ALTER TABLE "works" ADD COLUMN "hero_show_content" boolean DEFAULT true;
  ALTER TABLE "works" ADD COLUMN "industry" varchar;
  ALTER TABLE "works" ADD COLUMN "role" varchar;
  ALTER TABLE "works" ADD COLUMN "deliverables" varchar;
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "section_heading_eyebrow" varchar;
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "section_heading_content" jsonb;
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "slider_theme" "enum__works_v_blocks_content_columns_slider_theme" DEFAULT 'system';
  ALTER TABLE "_works_v_blocks_content" ADD COLUMN "container_width" "enum__works_v_blocks_content_container_width" DEFAULT 'contained';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "aspect_ratio" "enum__works_v_blocks_media_block_aspect_ratio" DEFAULT 'landscape';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "full_width" boolean DEFAULT false;
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "theme" "enum__works_v_blocks_media_block_theme" DEFAULT 'system';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "space_pt" "enum__works_v_blocks_media_block_space_pt" DEFAULT 'md';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "space_pb" "enum__works_v_blocks_media_block_space_pb" DEFAULT 'md';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "space_mt" "enum__works_v_blocks_media_block_space_mt" DEFAULT 'none';
  ALTER TABLE "_works_v_blocks_media_block" ADD COLUMN "space_mb" "enum__works_v_blocks_media_block_space_mb" DEFAULT 'none';
  ALTER TABLE "_works_v_blocks_slider" ADD COLUMN "theme" "enum__works_v_blocks_slider_theme" DEFAULT 'system';
  ALTER TABLE "_works_v_blocks_tabs_tabs" ADD COLUMN "slider_theme" "enum__works_v_blocks_tabs_tabs_slider_theme" DEFAULT 'system';
  ALTER TABLE "_works_v_blocks_tabs" ADD COLUMN "theme" "enum__works_v_blocks_tabs_theme" DEFAULT 'system';
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_show_content" boolean DEFAULT true;
  ALTER TABLE "_works_v" ADD COLUMN "version_industry" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_role" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_deliverables" varchar;
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_subheading";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_subheading";
  ALTER TABLE "works_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_subheading";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_heading";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_subheading";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'light';
  ALTER TABLE "works_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'light';
  ALTER TABLE "_works_v_blocks_content" ALTER COLUMN "theme" SET DEFAULT 'light';
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "section_heading_heading" varchar;
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "section_heading_subheading" varchar;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "section_heading_heading" varchar;
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "section_heading_subheading" varchar;
  ALTER TABLE "works_blocks_content_columns" ADD COLUMN "section_heading_heading" varchar;
  ALTER TABLE "works_blocks_content_columns" ADD COLUMN "section_heading_subheading" varchar;
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "section_heading_heading" varchar;
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "section_heading_subheading" varchar;
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_eyebrow";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_content";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "pages_blocks_content" DROP COLUMN IF EXISTS "container_width";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "aspect_ratio";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "full_width";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "space_pt";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "space_pb";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "space_mt";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN IF EXISTS "space_mb";
  ALTER TABLE "pages_blocks_slider" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "pages" DROP COLUMN IF EXISTS "hero_show_content";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_eyebrow";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_content";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN IF EXISTS "container_width";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "aspect_ratio";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "full_width";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "space_pt";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "space_pb";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "space_mt";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN IF EXISTS "space_mb";
  ALTER TABLE "_pages_v_blocks_slider" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "_pages_v" DROP COLUMN IF EXISTS "version_hero_show_content";
  ALTER TABLE "works_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_eyebrow";
  ALTER TABLE "works_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_content";
  ALTER TABLE "works_blocks_content_columns" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "works_blocks_content" DROP COLUMN IF EXISTS "container_width";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "aspect_ratio";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "full_width";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "space_pt";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "space_pb";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "space_mt";
  ALTER TABLE "works_blocks_media_block" DROP COLUMN IF EXISTS "space_mb";
  ALTER TABLE "works_blocks_slider" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "works_blocks_tabs_tabs" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "works_blocks_tabs" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "works" DROP COLUMN IF EXISTS "hero_show_content";
  ALTER TABLE "works" DROP COLUMN IF EXISTS "industry";
  ALTER TABLE "works" DROP COLUMN IF EXISTS "role";
  ALTER TABLE "works" DROP COLUMN IF EXISTS "deliverables";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_eyebrow";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN IF EXISTS "section_heading_content";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "_works_v_blocks_content" DROP COLUMN IF EXISTS "container_width";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "aspect_ratio";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "full_width";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "space_pt";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "space_pb";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "space_mt";
  ALTER TABLE "_works_v_blocks_media_block" DROP COLUMN IF EXISTS "space_mb";
  ALTER TABLE "_works_v_blocks_slider" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "_works_v_blocks_tabs_tabs" DROP COLUMN IF EXISTS "slider_theme";
  ALTER TABLE "_works_v_blocks_tabs" DROP COLUMN IF EXISTS "theme";
  ALTER TABLE "_works_v" DROP COLUMN IF EXISTS "version_hero_show_content";
  ALTER TABLE "_works_v" DROP COLUMN IF EXISTS "version_industry";
  ALTER TABLE "_works_v" DROP COLUMN IF EXISTS "version_role";
  ALTER TABLE "_works_v" DROP COLUMN IF EXISTS "version_deliverables";
  ALTER TABLE "public"."pages_blocks_content" ALTER COLUMN "theme" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_content_theme";
  CREATE TYPE "public"."enum_pages_blocks_content_theme" AS ENUM('light', 'dark');
  ALTER TABLE "public"."pages_blocks_content" ALTER COLUMN "theme" SET DATA TYPE "public"."enum_pages_blocks_content_theme" USING "theme"::"public"."enum_pages_blocks_content_theme";
  ALTER TABLE "public"."pages" ALTER COLUMN "hero_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_hero_type";
  CREATE TYPE "public"."enum_pages_hero_type" AS ENUM('none', 'highImpact', 'mediumImpact', 'lowImpact');
  ALTER TABLE "public"."pages" ALTER COLUMN "hero_type" SET DATA TYPE "public"."enum_pages_hero_type" USING "hero_type"::"public"."enum_pages_hero_type";
  ALTER TABLE "public"."_pages_v_blocks_content" ALTER COLUMN "theme" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_content_theme";
  CREATE TYPE "public"."enum__pages_v_blocks_content_theme" AS ENUM('light', 'dark');
  ALTER TABLE "public"."_pages_v_blocks_content" ALTER COLUMN "theme" SET DATA TYPE "public"."enum__pages_v_blocks_content_theme" USING "theme"::"public"."enum__pages_v_blocks_content_theme";
  ALTER TABLE "public"."_pages_v" ALTER COLUMN "version_hero_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_version_hero_type";
  CREATE TYPE "public"."enum__pages_v_version_hero_type" AS ENUM('none', 'highImpact', 'mediumImpact', 'lowImpact');
  ALTER TABLE "public"."_pages_v" ALTER COLUMN "version_hero_type" SET DATA TYPE "public"."enum__pages_v_version_hero_type" USING "version_hero_type"::"public"."enum__pages_v_version_hero_type";
  ALTER TABLE "public"."works_blocks_content" ALTER COLUMN "theme" SET DATA TYPE text;
  DROP TYPE "public"."enum_works_blocks_content_theme";
  CREATE TYPE "public"."enum_works_blocks_content_theme" AS ENUM('light', 'dark');
  ALTER TABLE "public"."works_blocks_content" ALTER COLUMN "theme" SET DATA TYPE "public"."enum_works_blocks_content_theme" USING "theme"::"public"."enum_works_blocks_content_theme";
  ALTER TABLE "public"."works" ALTER COLUMN "hero_type" SET DATA TYPE text;
  DROP TYPE "public"."enum_works_hero_type";
  CREATE TYPE "public"."enum_works_hero_type" AS ENUM('none', 'highImpact', 'mediumImpact', 'lowImpact');
  ALTER TABLE "public"."works" ALTER COLUMN "hero_type" SET DATA TYPE "public"."enum_works_hero_type" USING "hero_type"::"public"."enum_works_hero_type";
  ALTER TABLE "public"."_works_v_blocks_content" ALTER COLUMN "theme" SET DATA TYPE text;
  DROP TYPE "public"."enum__works_v_blocks_content_theme";
  CREATE TYPE "public"."enum__works_v_blocks_content_theme" AS ENUM('light', 'dark');
  ALTER TABLE "public"."_works_v_blocks_content" ALTER COLUMN "theme" SET DATA TYPE "public"."enum__works_v_blocks_content_theme" USING "theme"::"public"."enum__works_v_blocks_content_theme";
  ALTER TABLE "public"."_works_v" ALTER COLUMN "version_hero_type" SET DATA TYPE text;
  DROP TYPE "public"."enum__works_v_version_hero_type";
  CREATE TYPE "public"."enum__works_v_version_hero_type" AS ENUM('none', 'highImpact', 'mediumImpact', 'lowImpact');
  ALTER TABLE "public"."_works_v" ALTER COLUMN "version_hero_type" SET DATA TYPE "public"."enum__works_v_version_hero_type" USING "version_hero_type"::"public"."enum__works_v_version_hero_type";
  DROP TYPE "public"."enum_pages_blocks_content_columns_slider_theme";
  DROP TYPE "public"."enum_pages_blocks_content_container_width";
  DROP TYPE "public"."enum_pages_blocks_media_block_aspect_ratio";
  DROP TYPE "public"."enum_pages_blocks_media_block_theme";
  DROP TYPE "public"."enum_pages_blocks_media_block_space_pt";
  DROP TYPE "public"."enum_pages_blocks_media_block_space_pb";
  DROP TYPE "public"."enum_pages_blocks_media_block_space_mt";
  DROP TYPE "public"."enum_pages_blocks_media_block_space_mb";
  DROP TYPE "public"."enum_pages_blocks_slider_theme";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_slider_theme";
  DROP TYPE "public"."enum__pages_v_blocks_content_container_width";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_aspect_ratio";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_space_pt";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_space_pb";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_space_mt";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_space_mb";
  DROP TYPE "public"."enum__pages_v_blocks_slider_theme";
  DROP TYPE "public"."enum_works_blocks_content_columns_slider_theme";
  DROP TYPE "public"."enum_works_blocks_content_container_width";
  DROP TYPE "public"."enum_works_blocks_media_block_aspect_ratio";
  DROP TYPE "public"."enum_works_blocks_media_block_theme";
  DROP TYPE "public"."enum_works_blocks_media_block_space_pt";
  DROP TYPE "public"."enum_works_blocks_media_block_space_pb";
  DROP TYPE "public"."enum_works_blocks_media_block_space_mt";
  DROP TYPE "public"."enum_works_blocks_media_block_space_mb";
  DROP TYPE "public"."enum_works_blocks_slider_theme";
  DROP TYPE "public"."enum_works_blocks_tabs_tabs_slider_theme";
  DROP TYPE "public"."enum_works_blocks_tabs_theme";
  DROP TYPE "public"."enum__works_v_blocks_content_columns_slider_theme";
  DROP TYPE "public"."enum__works_v_blocks_content_container_width";
  DROP TYPE "public"."enum__works_v_blocks_media_block_aspect_ratio";
  DROP TYPE "public"."enum__works_v_blocks_media_block_theme";
  DROP TYPE "public"."enum__works_v_blocks_media_block_space_pt";
  DROP TYPE "public"."enum__works_v_blocks_media_block_space_pb";
  DROP TYPE "public"."enum__works_v_blocks_media_block_space_mt";
  DROP TYPE "public"."enum__works_v_blocks_media_block_space_mb";
  DROP TYPE "public"."enum__works_v_blocks_slider_theme";
  DROP TYPE "public"."enum__works_v_blocks_tabs_tabs_slider_theme";
  DROP TYPE "public"."enum__works_v_blocks_tabs_theme";`)
}
