import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_hero_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_pages_faq_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_pages_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum___pages_v_faq_v_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_posts_hero_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_posts_faq_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_posts_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__posts_v_version_hero_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum___posts_v_faq_v_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__posts_v_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_works_faq_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_works_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_works_blocks_cta_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum___works_v_faq_v_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__works_v_blocks_content_columns_text_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum__works_v_blocks_cta_links_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  CREATE TYPE "public"."enum_header_nav_items_link_index_page" AS ENUM('works', 'posts', 'contact', 'ask');
  ALTER TYPE "public"."enum_pages_hero_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_faq_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_pages_blocks_cta_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_version_hero_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum___pages_v_faq_v_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_posts_hero_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_posts_faq_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_posts_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__posts_v_version_hero_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum___posts_v_faq_v_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__posts_v_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_works_faq_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_works_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_works_blocks_cta_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum___works_v_faq_v_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__works_v_blocks_content_columns_text_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum__works_v_blocks_cta_links_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TYPE "public"."enum_header_nav_items_link_type" ADD VALUE 'index' BEFORE 'custom';
  ALTER TABLE "pages_hero_links" ADD COLUMN "link_index_page" "enum_pages_hero_links_link_index_page";
  ALTER TABLE "pages_faq" ADD COLUMN "link_index_page" "enum_pages_faq_link_index_page";
  ALTER TABLE "pages_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum_pages_blocks_content_columns_text_link_index_page";
  ALTER TABLE "pages_blocks_cta_links" ADD COLUMN "link_index_page" "enum_pages_blocks_cta_links_link_index_page";
  ALTER TABLE "_pages_v_version_hero_links" ADD COLUMN "link_index_page" "enum__pages_v_version_hero_links_link_index_page";
  ALTER TABLE "__pages_v_faq_v" ADD COLUMN "link_index_page" "enum___pages_v_faq_v_link_index_page";
  ALTER TABLE "_pages_v_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum__pages_v_blocks_content_columns_text_link_index_page";
  ALTER TABLE "_pages_v_blocks_cta_links" ADD COLUMN "link_index_page" "enum__pages_v_blocks_cta_links_link_index_page";
  ALTER TABLE "posts_hero_links" ADD COLUMN "link_index_page" "enum_posts_hero_links_link_index_page";
  ALTER TABLE "posts_faq" ADD COLUMN "link_index_page" "enum_posts_faq_link_index_page";
  ALTER TABLE "posts_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum_posts_blocks_content_columns_text_link_index_page";
  ALTER TABLE "_posts_v_version_hero_links" ADD COLUMN "link_index_page" "enum__posts_v_version_hero_links_link_index_page";
  ALTER TABLE "__posts_v_faq_v" ADD COLUMN "link_index_page" "enum___posts_v_faq_v_link_index_page";
  ALTER TABLE "_posts_v_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum__posts_v_blocks_content_columns_text_link_index_page";
  ALTER TABLE "works_faq" ADD COLUMN "link_index_page" "enum_works_faq_link_index_page";
  ALTER TABLE "works_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum_works_blocks_content_columns_text_link_index_page";
  ALTER TABLE "works_blocks_cta_links" ADD COLUMN "link_index_page" "enum_works_blocks_cta_links_link_index_page";
  ALTER TABLE "__works_v_faq_v" ADD COLUMN "link_index_page" "enum___works_v_faq_v_link_index_page";
  ALTER TABLE "_works_v_blocks_content_columns" ADD COLUMN "text_link_index_page" "enum__works_v_blocks_content_columns_text_link_index_page";
  ALTER TABLE "_works_v_blocks_cta_links" ADD COLUMN "link_index_page" "enum__works_v_blocks_cta_links_link_index_page";
  ALTER TABLE "header_nav_items" ADD COLUMN "link_index_page" "enum_header_nav_items_link_index_page";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_hero_links_link_type";
  CREATE TYPE "public"."enum_pages_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_hero_links_link_type" USING "link_type"::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_faq" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_faq_link_type";
  CREATE TYPE "public"."enum_pages_faq_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_faq_link_type";
  ALTER TABLE "pages_faq" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_faq_link_type" USING "link_type"::"public"."enum_pages_faq_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_content_columns_text_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum_pages_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum_pages_blocks_content_columns_text_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_type" USING "link_type"::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_version_hero_links_link_type" USING "link_type"::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "__pages_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__pages_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___pages_v_faq_v_link_type";
  CREATE TYPE "public"."enum___pages_v_faq_v_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__pages_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___pages_v_faq_v_link_type";
  ALTER TABLE "__pages_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___pages_v_faq_v_link_type" USING "link_type"::"public"."enum___pages_v_faq_v_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_content_columns_text_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum__pages_v_blocks_content_columns_text_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "posts_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "posts_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_posts_hero_links_link_type";
  CREATE TYPE "public"."enum_posts_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "posts_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_posts_hero_links_link_type";
  ALTER TABLE "posts_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_posts_hero_links_link_type" USING "link_type"::"public"."enum_posts_hero_links_link_type";
  ALTER TABLE "posts_faq" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "posts_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_posts_faq_link_type";
  CREATE TYPE "public"."enum_posts_faq_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "posts_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_posts_faq_link_type";
  ALTER TABLE "posts_faq" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_posts_faq_link_type" USING "link_type"::"public"."enum_posts_faq_link_type";
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_posts_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum_posts_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum_posts_blocks_content_columns_text_link_type";
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum_posts_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum_posts_blocks_content_columns_text_link_type";
  ALTER TABLE "_posts_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_posts_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__posts_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__posts_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_posts_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__posts_v_version_hero_links_link_type";
  ALTER TABLE "_posts_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__posts_v_version_hero_links_link_type" USING "link_type"::"public"."enum__posts_v_version_hero_links_link_type";
  ALTER TABLE "__posts_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__posts_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___posts_v_faq_v_link_type";
  CREATE TYPE "public"."enum___posts_v_faq_v_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__posts_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___posts_v_faq_v_link_type";
  ALTER TABLE "__posts_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___posts_v_faq_v_link_type" USING "link_type"::"public"."enum___posts_v_faq_v_link_type";
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__posts_v_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum__posts_v_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum__posts_v_blocks_content_columns_text_link_type";
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum__posts_v_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum__posts_v_blocks_content_columns_text_link_type";
  ALTER TABLE "works_faq" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "works_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_works_faq_link_type";
  CREATE TYPE "public"."enum_works_faq_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "works_faq" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_works_faq_link_type";
  ALTER TABLE "works_faq" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_works_faq_link_type" USING "link_type"::"public"."enum_works_faq_link_type";
  ALTER TABLE "works_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "works_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_works_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum_works_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "works_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum_works_blocks_content_columns_text_link_type";
  ALTER TABLE "works_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum_works_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum_works_blocks_content_columns_text_link_type";
  ALTER TABLE "works_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "works_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_works_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_works_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "works_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_works_blocks_cta_links_link_type";
  ALTER TABLE "works_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_works_blocks_cta_links_link_type" USING "link_type"::"public"."enum_works_blocks_cta_links_link_type";
  ALTER TABLE "__works_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "__works_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum___works_v_faq_v_link_type";
  CREATE TYPE "public"."enum___works_v_faq_v_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "__works_v_faq_v" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum___works_v_faq_v_link_type";
  ALTER TABLE "__works_v_faq_v" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum___works_v_faq_v_link_type" USING "link_type"::"public"."enum___works_v_faq_v_link_type";
  ALTER TABLE "_works_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE text;
  ALTER TABLE "_works_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__works_v_blocks_content_columns_text_link_type";
  CREATE TYPE "public"."enum__works_v_blocks_content_columns_text_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_works_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DEFAULT 'reference'::"public"."enum__works_v_blocks_content_columns_text_link_type";
  ALTER TABLE "_works_v_blocks_content_columns" ALTER COLUMN "text_link_type" SET DATA TYPE "public"."enum__works_v_blocks_content_columns_text_link_type" USING "text_link_type"::"public"."enum__works_v_blocks_content_columns_text_link_type";
  ALTER TABLE "_works_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_works_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__works_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__works_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_works_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__works_v_blocks_cta_links_link_type";
  ALTER TABLE "_works_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__works_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__works_v_blocks_cta_links_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_header_nav_items_link_type";
  CREATE TYPE "public"."enum_header_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_header_nav_items_link_type" USING "link_type"::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "pages_hero_links" DROP COLUMN "link_index_page";
  ALTER TABLE "pages_faq" DROP COLUMN "link_index_page";
  ALTER TABLE "pages_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "pages_blocks_cta_links" DROP COLUMN "link_index_page";
  ALTER TABLE "_pages_v_version_hero_links" DROP COLUMN "link_index_page";
  ALTER TABLE "__pages_v_faq_v" DROP COLUMN "link_index_page";
  ALTER TABLE "_pages_v_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "_pages_v_blocks_cta_links" DROP COLUMN "link_index_page";
  ALTER TABLE "posts_hero_links" DROP COLUMN "link_index_page";
  ALTER TABLE "posts_faq" DROP COLUMN "link_index_page";
  ALTER TABLE "posts_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "_posts_v_version_hero_links" DROP COLUMN "link_index_page";
  ALTER TABLE "__posts_v_faq_v" DROP COLUMN "link_index_page";
  ALTER TABLE "_posts_v_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "works_faq" DROP COLUMN "link_index_page";
  ALTER TABLE "works_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "works_blocks_cta_links" DROP COLUMN "link_index_page";
  ALTER TABLE "__works_v_faq_v" DROP COLUMN "link_index_page";
  ALTER TABLE "_works_v_blocks_content_columns" DROP COLUMN "text_link_index_page";
  ALTER TABLE "_works_v_blocks_cta_links" DROP COLUMN "link_index_page";
  ALTER TABLE "header_nav_items" DROP COLUMN "link_index_page";
  DROP TYPE "public"."enum_pages_hero_links_link_index_page";
  DROP TYPE "public"."enum_pages_faq_link_index_page";
  DROP TYPE "public"."enum_pages_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_index_page";
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_index_page";
  DROP TYPE "public"."enum___pages_v_faq_v_link_index_page";
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_index_page";
  DROP TYPE "public"."enum_posts_hero_links_link_index_page";
  DROP TYPE "public"."enum_posts_faq_link_index_page";
  DROP TYPE "public"."enum_posts_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum__posts_v_version_hero_links_link_index_page";
  DROP TYPE "public"."enum___posts_v_faq_v_link_index_page";
  DROP TYPE "public"."enum__posts_v_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum_works_faq_link_index_page";
  DROP TYPE "public"."enum_works_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum_works_blocks_cta_links_link_index_page";
  DROP TYPE "public"."enum___works_v_faq_v_link_index_page";
  DROP TYPE "public"."enum__works_v_blocks_content_columns_text_link_index_page";
  DROP TYPE "public"."enum__works_v_blocks_cta_links_link_index_page";
  DROP TYPE "public"."enum_header_nav_items_link_index_page";`)
}
