import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum_pages_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__pages_v_version_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum__pages_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_posts_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum_posts_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__posts_v_version_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum__posts_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum_works_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum_works_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  CREATE TYPE "public"."enum__works_v_version_hero_visual_type" AS ENUM('media', 'streakField', 'lightLeak');
  CREATE TYPE "public"."enum__works_v_version_hero_shader_origin" AS ENUM('top-right', 'top-left', 'bottom-right', 'bottom-left');
  ALTER TABLE "pages" ADD COLUMN "hero_visual_type" "enum_pages_hero_visual_type";
  ALTER TABLE "pages" ADD COLUMN "hero_shader_studio_id" integer;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_preset" varchar;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_seed" numeric;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_speed" numeric;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_intensity" numeric;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_origin" "enum_pages_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "pages" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "pages" ADD COLUMN "hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "pages" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "pages" ADD COLUMN "hero_shader_poster_media_id" integer;
  ALTER TABLE "pages" ADD COLUMN "show_contents" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_visual_type" "enum__pages_v_version_hero_visual_type";
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_studio_id" integer;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_preset" varchar;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_seed" numeric;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_speed" numeric;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_intensity" numeric;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_origin" "enum__pages_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "_pages_v" ADD COLUMN "version_hero_shader_poster_media_id" integer;
  ALTER TABLE "_pages_v" ADD COLUMN "version_show_contents" boolean DEFAULT false;
  ALTER TABLE "posts" ADD COLUMN "hero_visual_type" "enum_posts_hero_visual_type";
  ALTER TABLE "posts" ADD COLUMN "hero_shader_studio_id" integer;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_preset" varchar;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_seed" numeric;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_speed" numeric;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_intensity" numeric;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_origin" "enum_posts_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "posts" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "posts" ADD COLUMN "hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "posts" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "posts" ADD COLUMN "hero_shader_poster_media_id" integer;
  ALTER TABLE "posts" ADD COLUMN "intro_eyebrow" varchar;
  ALTER TABLE "posts" ADD COLUMN "intro_title" varchar;
  ALTER TABLE "posts" ADD COLUMN "intro_body" jsonb;
  ALTER TABLE "posts" ADD COLUMN "show_contents" boolean DEFAULT false;
  ALTER TABLE "posts" ADD COLUMN "hide_related_posts" boolean DEFAULT false;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_visual_type" "enum__posts_v_version_hero_visual_type";
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_studio_id" integer;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_preset" varchar;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_seed" numeric;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_speed" numeric;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_intensity" numeric;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_origin" "enum__posts_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hero_shader_poster_media_id" integer;
  ALTER TABLE "_posts_v" ADD COLUMN "version_intro_eyebrow" varchar;
  ALTER TABLE "_posts_v" ADD COLUMN "version_intro_title" varchar;
  ALTER TABLE "_posts_v" ADD COLUMN "version_intro_body" jsonb;
  ALTER TABLE "_posts_v" ADD COLUMN "version_show_contents" boolean DEFAULT false;
  ALTER TABLE "_posts_v" ADD COLUMN "version_hide_related_posts" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "hero_visual_type" "enum_works_hero_visual_type";
  ALTER TABLE "works" ADD COLUMN "hero_shader_studio_id" integer;
  ALTER TABLE "works" ADD COLUMN "hero_shader_preset" varchar;
  ALTER TABLE "works" ADD COLUMN "hero_shader_seed" numeric;
  ALTER TABLE "works" ADD COLUMN "hero_shader_speed" numeric;
  ALTER TABLE "works" ADD COLUMN "hero_shader_intensity" numeric;
  ALTER TABLE "works" ADD COLUMN "hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "hero_shader_origin" "enum_works_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "works" ADD COLUMN "hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "works" ADD COLUMN "hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "works" ADD COLUMN "hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "works" ADD COLUMN "hero_shader_section_hover" numeric;
  ALTER TABLE "works" ADD COLUMN "hero_shader_poster_media_id" integer;
  ALTER TABLE "works" ADD COLUMN "intro_eyebrow" varchar;
  ALTER TABLE "works" ADD COLUMN "intro_title" varchar;
  ALTER TABLE "works" ADD COLUMN "intro_body" jsonb;
  ALTER TABLE "works" ADD COLUMN "show_contents" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_visual_type" "enum__works_v_version_hero_visual_type";
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_studio_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_preset" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_seed" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_speed" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_intensity" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_bleed" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_origin" "enum__works_v_version_hero_shader_origin" DEFAULT 'top-right';
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_show_media" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_surface" "enum_visual_surface" DEFAULT 'auto';
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_pointer_interaction" boolean DEFAULT false;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_hover_targets" "enum_leak_hover_targets";
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_section_hover" numeric;
  ALTER TABLE "_works_v" ADD COLUMN "version_hero_shader_poster_media_id" integer;
  ALTER TABLE "_works_v" ADD COLUMN "version_intro_eyebrow" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_intro_title" varchar;
  ALTER TABLE "_works_v" ADD COLUMN "version_intro_body" jsonb;
  ALTER TABLE "_works_v" ADD COLUMN "version_show_contents" boolean DEFAULT false;
  ALTER TABLE "pages" ADD CONSTRAINT "pages_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages" ADD CONSTRAINT "pages_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("version_hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("version_hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts" ADD CONSTRAINT "posts_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts" ADD CONSTRAINT "posts_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_posts_v" ADD CONSTRAINT "_posts_v_version_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("version_hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_posts_v" ADD CONSTRAINT "_posts_v_version_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("version_hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "works" ADD CONSTRAINT "works_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_hero_shader_studio_id_streak_looks_id_fk" FOREIGN KEY ("version_hero_shader_studio_id") REFERENCES "public"."streak_looks"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_works_v" ADD CONSTRAINT "_works_v_version_hero_shader_poster_media_id_media_id_fk" FOREIGN KEY ("version_hero_shader_poster_media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "pages_hero_shader_hero_shader_studio_idx" ON "pages" USING btree ("hero_shader_studio_id");
  CREATE INDEX "pages_hero_shader_hero_shader_poster_media_idx" ON "pages" USING btree ("hero_shader_poster_media_id");
  CREATE INDEX "_pages_v_version_hero_shader_version_hero_shader_studio_idx" ON "_pages_v" USING btree ("version_hero_shader_studio_id");
  CREATE INDEX "_pages_v_version_hero_shader_version_hero_shader_poster__idx" ON "_pages_v" USING btree ("version_hero_shader_poster_media_id");
  CREATE INDEX "posts_hero_shader_hero_shader_studio_idx" ON "posts" USING btree ("hero_shader_studio_id");
  CREATE INDEX "posts_hero_shader_hero_shader_poster_media_idx" ON "posts" USING btree ("hero_shader_poster_media_id");
  CREATE INDEX "_posts_v_version_hero_shader_version_hero_shader_studio_idx" ON "_posts_v" USING btree ("version_hero_shader_studio_id");
  CREATE INDEX "_posts_v_version_hero_shader_version_hero_shader_poster__idx" ON "_posts_v" USING btree ("version_hero_shader_poster_media_id");
  CREATE INDEX "works_hero_shader_hero_shader_studio_idx" ON "works" USING btree ("hero_shader_studio_id");
  CREATE INDEX "works_hero_shader_hero_shader_poster_media_idx" ON "works" USING btree ("hero_shader_poster_media_id");
  CREATE INDEX "_works_v_version_hero_shader_version_hero_shader_studio_idx" ON "_works_v" USING btree ("version_hero_shader_studio_id");
  CREATE INDEX "_works_v_version_hero_shader_version_hero_shader_poster__idx" ON "_works_v" USING btree ("version_hero_shader_poster_media_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages" DROP CONSTRAINT "pages_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "pages" DROP CONSTRAINT "pages_hero_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_pages_v" DROP CONSTRAINT "_pages_v_version_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "_pages_v" DROP CONSTRAINT "_pages_v_version_hero_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "posts" DROP CONSTRAINT "posts_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "posts" DROP CONSTRAINT "posts_hero_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_posts_v" DROP CONSTRAINT "_posts_v_version_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "_posts_v" DROP CONSTRAINT "_posts_v_version_hero_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT "works_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "works" DROP CONSTRAINT "works_hero_shader_poster_media_id_media_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT "_works_v_version_hero_shader_studio_id_streak_looks_id_fk";
  
  ALTER TABLE "_works_v" DROP CONSTRAINT "_works_v_version_hero_shader_poster_media_id_media_id_fk";
  
  DROP INDEX "pages_hero_shader_hero_shader_studio_idx";
  DROP INDEX "pages_hero_shader_hero_shader_poster_media_idx";
  DROP INDEX "_pages_v_version_hero_shader_version_hero_shader_studio_idx";
  DROP INDEX "_pages_v_version_hero_shader_version_hero_shader_poster__idx";
  DROP INDEX "posts_hero_shader_hero_shader_studio_idx";
  DROP INDEX "posts_hero_shader_hero_shader_poster_media_idx";
  DROP INDEX "_posts_v_version_hero_shader_version_hero_shader_studio_idx";
  DROP INDEX "_posts_v_version_hero_shader_version_hero_shader_poster__idx";
  DROP INDEX "works_hero_shader_hero_shader_studio_idx";
  DROP INDEX "works_hero_shader_hero_shader_poster_media_idx";
  DROP INDEX "_works_v_version_hero_shader_version_hero_shader_studio_idx";
  DROP INDEX "_works_v_version_hero_shader_version_hero_shader_poster__idx";
  ALTER TABLE "pages" DROP COLUMN "hero_visual_type";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_studio_id";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_preset";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_seed";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_speed";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_intensity";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_pointer_interaction";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "pages" DROP COLUMN "hero_shader_poster_media_id";
  ALTER TABLE "pages" DROP COLUMN "show_contents";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_visual_type";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_studio_id";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_preset";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_seed";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_speed";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_intensity";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_pointer_interaction";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "_pages_v" DROP COLUMN "version_hero_shader_poster_media_id";
  ALTER TABLE "_pages_v" DROP COLUMN "version_show_contents";
  ALTER TABLE "posts" DROP COLUMN "hero_visual_type";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_studio_id";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_preset";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_seed";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_speed";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_intensity";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_pointer_interaction";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "posts" DROP COLUMN "hero_shader_poster_media_id";
  ALTER TABLE "posts" DROP COLUMN "intro_eyebrow";
  ALTER TABLE "posts" DROP COLUMN "intro_title";
  ALTER TABLE "posts" DROP COLUMN "intro_body";
  ALTER TABLE "posts" DROP COLUMN "show_contents";
  ALTER TABLE "posts" DROP COLUMN "hide_related_posts";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_visual_type";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_studio_id";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_preset";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_seed";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_speed";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_intensity";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_pointer_interaction";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hero_shader_poster_media_id";
  ALTER TABLE "_posts_v" DROP COLUMN "version_intro_eyebrow";
  ALTER TABLE "_posts_v" DROP COLUMN "version_intro_title";
  ALTER TABLE "_posts_v" DROP COLUMN "version_intro_body";
  ALTER TABLE "_posts_v" DROP COLUMN "version_show_contents";
  ALTER TABLE "_posts_v" DROP COLUMN "version_hide_related_posts";
  ALTER TABLE "works" DROP COLUMN "hero_visual_type";
  ALTER TABLE "works" DROP COLUMN "hero_shader_studio_id";
  ALTER TABLE "works" DROP COLUMN "hero_shader_preset";
  ALTER TABLE "works" DROP COLUMN "hero_shader_seed";
  ALTER TABLE "works" DROP COLUMN "hero_shader_speed";
  ALTER TABLE "works" DROP COLUMN "hero_shader_intensity";
  ALTER TABLE "works" DROP COLUMN "hero_shader_bleed";
  ALTER TABLE "works" DROP COLUMN "hero_shader_origin";
  ALTER TABLE "works" DROP COLUMN "hero_shader_show_media";
  ALTER TABLE "works" DROP COLUMN "hero_shader_surface";
  ALTER TABLE "works" DROP COLUMN "hero_shader_pointer_interaction";
  ALTER TABLE "works" DROP COLUMN "hero_shader_hover_targets";
  ALTER TABLE "works" DROP COLUMN "hero_shader_section_hover";
  ALTER TABLE "works" DROP COLUMN "hero_shader_poster_media_id";
  ALTER TABLE "works" DROP COLUMN "intro_eyebrow";
  ALTER TABLE "works" DROP COLUMN "intro_title";
  ALTER TABLE "works" DROP COLUMN "intro_body";
  ALTER TABLE "works" DROP COLUMN "show_contents";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_visual_type";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_studio_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_preset";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_seed";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_speed";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_intensity";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_bleed";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_origin";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_show_media";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_surface";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_pointer_interaction";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_hover_targets";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_section_hover";
  ALTER TABLE "_works_v" DROP COLUMN "version_hero_shader_poster_media_id";
  ALTER TABLE "_works_v" DROP COLUMN "version_intro_eyebrow";
  ALTER TABLE "_works_v" DROP COLUMN "version_intro_title";
  ALTER TABLE "_works_v" DROP COLUMN "version_intro_body";
  ALTER TABLE "_works_v" DROP COLUMN "version_show_contents";
  DROP TYPE "public"."enum_pages_hero_visual_type";
  DROP TYPE "public"."enum_pages_hero_shader_origin";
  DROP TYPE "public"."enum__pages_v_version_hero_visual_type";
  DROP TYPE "public"."enum__pages_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_posts_hero_visual_type";
  DROP TYPE "public"."enum_posts_hero_shader_origin";
  DROP TYPE "public"."enum__posts_v_version_hero_visual_type";
  DROP TYPE "public"."enum__posts_v_version_hero_shader_origin";
  DROP TYPE "public"."enum_works_hero_visual_type";
  DROP TYPE "public"."enum_works_hero_shader_origin";
  DROP TYPE "public"."enum__works_v_version_hero_visual_type";
  DROP TYPE "public"."enum__works_v_version_hero_shader_origin";`)
}
