import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_transition_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_full_media_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_media_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_split_narrow_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_image_pair_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_split_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_rich_text_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_faq_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_pages_insight_list_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_transition_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_full_media_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_media_split_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_split_narrow_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_image_pair_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_split_offset_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_rich_text_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_faq_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___pages_v_insight_list_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_transition_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_full_media_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_media_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_split_narrow_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_image_pair_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_split_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_rich_text_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_faq_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_posts_insight_list_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_transition_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_full_media_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_media_split_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_split_narrow_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_image_pair_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_split_offset_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_rich_text_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_faq_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___posts_v_insight_list_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_transition_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_full_media_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_media_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_split_narrow_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_image_pair_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_split_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_rich_text_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_faq_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum_works_insight_list_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_transition_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__works_v_blocks_feature_heading_offset_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_full_media_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_media_split_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_split_narrow_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__works_v_blocks_carousel_split_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_image_pair_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_split_offset_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_rich_text_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_faq_v_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__works_v_blocks_carousel_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum__works_v_blocks_feature_tabs_text_size" AS ENUM('small', 'large');
  CREATE TYPE "public"."enum___works_v_insight_list_v_text_size" AS ENUM('small', 'large');
  ALTER TABLE "pages_caption" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "pages_caption" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_pages_caption_size";
  CREATE TYPE "public"."enum_pages_caption_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_pages_caption_size" USING "size"::"public"."enum_pages_caption_size";
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "pages_youtube" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_pages_youtube_size";
  CREATE TYPE "public"."enum_pages_youtube_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_pages_youtube_size" USING "size"::"public"."enum_pages_youtube_size";
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__pages_v_caption_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___pages_v_caption_v_size";
  CREATE TYPE "public"."enum___pages_v_caption_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___pages_v_caption_v_size" USING "size"::"public"."enum___pages_v_caption_v_size";
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__pages_v_youtube_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___pages_v_youtube_v_size";
  CREATE TYPE "public"."enum___pages_v_youtube_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___pages_v_youtube_v_size" USING "size"::"public"."enum___pages_v_youtube_v_size";
  ALTER TABLE "posts_caption" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "posts_caption" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_posts_caption_size";
  CREATE TYPE "public"."enum_posts_caption_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_posts_caption_size" USING "size"::"public"."enum_posts_caption_size";
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "posts_youtube" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_posts_youtube_size";
  CREATE TYPE "public"."enum_posts_youtube_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_posts_youtube_size" USING "size"::"public"."enum_posts_youtube_size";
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__posts_v_caption_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___posts_v_caption_v_size";
  CREATE TYPE "public"."enum___posts_v_caption_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___posts_v_caption_v_size" USING "size"::"public"."enum___posts_v_caption_v_size";
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__posts_v_youtube_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___posts_v_youtube_v_size";
  CREATE TYPE "public"."enum___posts_v_youtube_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___posts_v_youtube_v_size" USING "size"::"public"."enum___posts_v_youtube_v_size";
  ALTER TABLE "works_caption" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "works_caption" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_works_caption_size";
  CREATE TYPE "public"."enum_works_caption_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_works_caption_size" USING "size"::"public"."enum_works_caption_size";
  ALTER TABLE "works_youtube" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "works_youtube" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum_works_youtube_size";
  CREATE TYPE "public"."enum_works_youtube_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_works_youtube_size" USING "size"::"public"."enum_works_youtube_size";
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__works_v_caption_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___works_v_caption_v_size";
  CREATE TYPE "public"."enum___works_v_caption_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___works_v_caption_v_size" USING "size"::"public"."enum___works_v_caption_v_size";
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" DROP DEFAULT;
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__works_v_youtube_v" SET "size" = 'contained' WHERE "size" = 'full';
  DROP TYPE "public"."enum___works_v_youtube_v_size";
  CREATE TYPE "public"."enum___works_v_youtube_v_size" AS ENUM('full', 'contained', 'inset', 'small');
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___works_v_youtube_v_size" USING "size"::"public"."enum___works_v_youtube_v_size";
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "pages_image_statement" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum_pages_image_statement_text_size";
  CREATE TYPE "public"."enum_pages_image_statement_text_size" AS ENUM('small', 'large');
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum_pages_image_statement_text_size";
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_pages_image_statement_text_size" USING "text_size"::"public"."enum_pages_image_statement_text_size";
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__pages_v_image_statement_v" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum___pages_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___pages_v_image_statement_v_text_size" AS ENUM('small', 'large');
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum___pages_v_image_statement_v_text_size";
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___pages_v_image_statement_v_text_size" USING "text_size"::"public"."enum___pages_v_image_statement_v_text_size";
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "posts_image_statement" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum_posts_image_statement_text_size";
  CREATE TYPE "public"."enum_posts_image_statement_text_size" AS ENUM('small', 'large');
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum_posts_image_statement_text_size";
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_posts_image_statement_text_size" USING "text_size"::"public"."enum_posts_image_statement_text_size";
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__posts_v_image_statement_v" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum___posts_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___posts_v_image_statement_v_text_size" AS ENUM('small', 'large');
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum___posts_v_image_statement_v_text_size";
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___posts_v_image_statement_v_text_size" USING "text_size"::"public"."enum___posts_v_image_statement_v_text_size";
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "works_image_statement" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum_works_image_statement_text_size";
  CREATE TYPE "public"."enum_works_image_statement_text_size" AS ENUM('small', 'large');
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum_works_image_statement_text_size";
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_works_image_statement_text_size" USING "text_size"::"public"."enum_works_image_statement_text_size";
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__works_v_image_statement_v" SET "text_size" = 'large' WHERE "text_size" = 'default';
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::text;
  DROP TYPE "public"."enum___works_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___works_v_image_statement_v_text_size" AS ENUM('small', 'large');
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'small'::"public"."enum___works_v_image_statement_v_text_size";
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___works_v_image_statement_v_text_size" USING "text_size"::"public"."enum___works_v_image_statement_v_text_size";
  ALTER TABLE "pages_transition" ADD COLUMN "text_size" "enum_pages_transition_text_size" DEFAULT 'small';
  ALTER TABLE "pages_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum_pages_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "pages_full_media" ADD COLUMN "text_size" "enum_pages_full_media_text_size" DEFAULT 'small';
  ALTER TABLE "pages_media_split" ADD COLUMN "text_size" "enum_pages_media_split_text_size" DEFAULT 'small';
  ALTER TABLE "pages_split_narrow" ADD COLUMN "text_size" "enum_pages_split_narrow_text_size" DEFAULT 'small';
  ALTER TABLE "pages_blocks_carousel_split" ADD COLUMN "text_size" "enum_pages_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "pages_image_pair" ADD COLUMN "text_size" "enum_pages_image_pair_text_size" DEFAULT 'small';
  ALTER TABLE "pages_split_offset" ADD COLUMN "text_size" "enum_pages_split_offset_text_size" DEFAULT 'small';
  ALTER TABLE "pages_rich_text" ADD COLUMN "text_size" "enum_pages_rich_text_text_size" DEFAULT 'small';
  ALTER TABLE "pages_faq" ADD COLUMN "text_size" "enum_pages_faq_text_size" DEFAULT 'small';
  ALTER TABLE "pages_blocks_carousel_tabs" ADD COLUMN "text_size" "enum_pages_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "pages_blocks_feature_tabs" ADD COLUMN "text_size" "enum_pages_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "pages_insight_list" ADD COLUMN "text_size" "enum_pages_insight_list_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_transition_v" ADD COLUMN "text_size" "enum___pages_v_transition_v_text_size" DEFAULT 'small';
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum__pages_v_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_full_media_v" ADD COLUMN "text_size" "enum___pages_v_full_media_v_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_media_split_v" ADD COLUMN "text_size" "enum___pages_v_media_split_v_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_split_narrow_v" ADD COLUMN "text_size" "enum___pages_v_split_narrow_v_text_size" DEFAULT 'small';
  ALTER TABLE "_pages_v_blocks_carousel_split" ADD COLUMN "text_size" "enum__pages_v_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_image_pair_v" ADD COLUMN "text_size" "enum___pages_v_image_pair_v_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_split_offset_v" ADD COLUMN "text_size" "enum___pages_v_split_offset_v_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_rich_text_v" ADD COLUMN "text_size" "enum___pages_v_rich_text_v_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_faq_v" ADD COLUMN "text_size" "enum___pages_v_faq_v_text_size" DEFAULT 'small';
  ALTER TABLE "_pages_v_blocks_carousel_tabs" ADD COLUMN "text_size" "enum__pages_v_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "_pages_v_blocks_feature_tabs" ADD COLUMN "text_size" "enum__pages_v_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "__pages_v_insight_list_v" ADD COLUMN "text_size" "enum___pages_v_insight_list_v_text_size" DEFAULT 'small';
  ALTER TABLE "posts_transition" ADD COLUMN "text_size" "enum_posts_transition_text_size" DEFAULT 'small';
  ALTER TABLE "posts_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum_posts_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "posts_full_media" ADD COLUMN "text_size" "enum_posts_full_media_text_size" DEFAULT 'small';
  ALTER TABLE "posts_media_split" ADD COLUMN "text_size" "enum_posts_media_split_text_size" DEFAULT 'small';
  ALTER TABLE "posts_split_narrow" ADD COLUMN "text_size" "enum_posts_split_narrow_text_size" DEFAULT 'small';
  ALTER TABLE "posts_blocks_carousel_split" ADD COLUMN "text_size" "enum_posts_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "posts_image_pair" ADD COLUMN "text_size" "enum_posts_image_pair_text_size" DEFAULT 'small';
  ALTER TABLE "posts_split_offset" ADD COLUMN "text_size" "enum_posts_split_offset_text_size" DEFAULT 'small';
  ALTER TABLE "posts_rich_text" ADD COLUMN "text_size" "enum_posts_rich_text_text_size" DEFAULT 'small';
  ALTER TABLE "posts_faq" ADD COLUMN "text_size" "enum_posts_faq_text_size" DEFAULT 'small';
  ALTER TABLE "posts_blocks_carousel_tabs" ADD COLUMN "text_size" "enum_posts_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "posts_blocks_feature_tabs" ADD COLUMN "text_size" "enum_posts_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "posts_insight_list" ADD COLUMN "text_size" "enum_posts_insight_list_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_transition_v" ADD COLUMN "text_size" "enum___posts_v_transition_v_text_size" DEFAULT 'small';
  ALTER TABLE "_posts_v_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum__posts_v_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_full_media_v" ADD COLUMN "text_size" "enum___posts_v_full_media_v_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_media_split_v" ADD COLUMN "text_size" "enum___posts_v_media_split_v_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_split_narrow_v" ADD COLUMN "text_size" "enum___posts_v_split_narrow_v_text_size" DEFAULT 'small';
  ALTER TABLE "_posts_v_blocks_carousel_split" ADD COLUMN "text_size" "enum__posts_v_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_image_pair_v" ADD COLUMN "text_size" "enum___posts_v_image_pair_v_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_split_offset_v" ADD COLUMN "text_size" "enum___posts_v_split_offset_v_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_rich_text_v" ADD COLUMN "text_size" "enum___posts_v_rich_text_v_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_faq_v" ADD COLUMN "text_size" "enum___posts_v_faq_v_text_size" DEFAULT 'small';
  ALTER TABLE "_posts_v_blocks_carousel_tabs" ADD COLUMN "text_size" "enum__posts_v_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "_posts_v_blocks_feature_tabs" ADD COLUMN "text_size" "enum__posts_v_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "__posts_v_insight_list_v" ADD COLUMN "text_size" "enum___posts_v_insight_list_v_text_size" DEFAULT 'small';
  ALTER TABLE "works_transition" ADD COLUMN "text_size" "enum_works_transition_text_size" DEFAULT 'small';
  ALTER TABLE "works_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum_works_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "works_full_media" ADD COLUMN "text_size" "enum_works_full_media_text_size" DEFAULT 'small';
  ALTER TABLE "works_media_split" ADD COLUMN "text_size" "enum_works_media_split_text_size" DEFAULT 'small';
  ALTER TABLE "works_split_narrow" ADD COLUMN "text_size" "enum_works_split_narrow_text_size" DEFAULT 'small';
  ALTER TABLE "works_blocks_carousel_split" ADD COLUMN "text_size" "enum_works_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "works_image_pair" ADD COLUMN "text_size" "enum_works_image_pair_text_size" DEFAULT 'small';
  ALTER TABLE "works_split_offset" ADD COLUMN "text_size" "enum_works_split_offset_text_size" DEFAULT 'small';
  ALTER TABLE "works_rich_text" ADD COLUMN "text_size" "enum_works_rich_text_text_size" DEFAULT 'small';
  ALTER TABLE "works_faq" ADD COLUMN "text_size" "enum_works_faq_text_size" DEFAULT 'small';
  ALTER TABLE "works_blocks_carousel_tabs" ADD COLUMN "text_size" "enum_works_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "works_blocks_feature_tabs" ADD COLUMN "text_size" "enum_works_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "works_insight_list" ADD COLUMN "text_size" "enum_works_insight_list_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_transition_v" ADD COLUMN "text_size" "enum___works_v_transition_v_text_size" DEFAULT 'small';
  ALTER TABLE "_works_v_blocks_feature_heading_offset" ADD COLUMN "text_size" "enum__works_v_blocks_feature_heading_offset_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_full_media_v" ADD COLUMN "text_size" "enum___works_v_full_media_v_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_media_split_v" ADD COLUMN "text_size" "enum___works_v_media_split_v_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_split_narrow_v" ADD COLUMN "text_size" "enum___works_v_split_narrow_v_text_size" DEFAULT 'small';
  ALTER TABLE "_works_v_blocks_carousel_split" ADD COLUMN "text_size" "enum__works_v_blocks_carousel_split_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_image_pair_v" ADD COLUMN "text_size" "enum___works_v_image_pair_v_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_split_offset_v" ADD COLUMN "text_size" "enum___works_v_split_offset_v_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_rich_text_v" ADD COLUMN "text_size" "enum___works_v_rich_text_v_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_faq_v" ADD COLUMN "text_size" "enum___works_v_faq_v_text_size" DEFAULT 'small';
  ALTER TABLE "_works_v_blocks_carousel_tabs" ADD COLUMN "text_size" "enum__works_v_blocks_carousel_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "_works_v_blocks_feature_tabs" ADD COLUMN "text_size" "enum__works_v_blocks_feature_tabs_text_size" DEFAULT 'small';
  ALTER TABLE "__works_v_insight_list_v" ADD COLUMN "text_size" "enum___works_v_insight_list_v_text_size" DEFAULT 'small';
  UPDATE "pages_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "pages_blocks_feature_heading_offset" DROP COLUMN "body_size";
  UPDATE "_pages_v_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" DROP COLUMN "body_size";
  UPDATE "posts_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "posts_blocks_feature_heading_offset" DROP COLUMN "body_size";
  UPDATE "_posts_v_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "_posts_v_blocks_feature_heading_offset" DROP COLUMN "body_size";
  UPDATE "works_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "works_blocks_feature_heading_offset" DROP COLUMN "body_size";
  UPDATE "_works_v_blocks_feature_heading_offset" SET "text_size" = 'large' WHERE "body_size" = 'large';
  ALTER TABLE "_works_v_blocks_feature_heading_offset" DROP COLUMN "body_size";
  DROP TYPE "public"."enum_pages_blocks_feature_heading_offset_body_size";
  DROP TYPE "public"."enum__pages_v_blocks_feature_heading_offset_body_size";
  DROP TYPE "public"."enum_posts_blocks_feature_heading_offset_body_size";
  DROP TYPE "public"."enum__posts_v_blocks_feature_heading_offset_body_size";
  DROP TYPE "public"."enum_works_blocks_feature_heading_offset_body_size";
  DROP TYPE "public"."enum__works_v_blocks_feature_heading_offset_body_size";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  CREATE TYPE "public"."enum_posts_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  CREATE TYPE "public"."enum_works_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  CREATE TYPE "public"."enum__works_v_blocks_feature_heading_offset_body_size" AS ENUM('small', 'medium', 'large');
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "pages_image_statement" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_pages_image_statement_text_size";
  CREATE TYPE "public"."enum_pages_image_statement_text_size" AS ENUM('default', 'small');
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum_pages_image_statement_text_size";
  ALTER TABLE "pages_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_pages_image_statement_text_size" USING "text_size"::"public"."enum_pages_image_statement_text_size";
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "pages_caption" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_pages_caption_size";
  CREATE TYPE "public"."enum_pages_caption_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_pages_caption_size";
  ALTER TABLE "pages_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_pages_caption_size" USING "size"::"public"."enum_pages_caption_size";
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "pages_youtube" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_pages_youtube_size";
  CREATE TYPE "public"."enum_pages_youtube_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_pages_youtube_size";
  ALTER TABLE "pages_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_pages_youtube_size" USING "size"::"public"."enum_pages_youtube_size";
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__pages_v_image_statement_v" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum___pages_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___pages_v_image_statement_v_text_size" AS ENUM('default', 'small');
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum___pages_v_image_statement_v_text_size";
  ALTER TABLE "__pages_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___pages_v_image_statement_v_text_size" USING "text_size"::"public"."enum___pages_v_image_statement_v_text_size";
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__pages_v_caption_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___pages_v_caption_v_size";
  CREATE TYPE "public"."enum___pages_v_caption_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___pages_v_caption_v_size";
  ALTER TABLE "__pages_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___pages_v_caption_v_size" USING "size"::"public"."enum___pages_v_caption_v_size";
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__pages_v_youtube_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___pages_v_youtube_v_size";
  CREATE TYPE "public"."enum___pages_v_youtube_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___pages_v_youtube_v_size";
  ALTER TABLE "__pages_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___pages_v_youtube_v_size" USING "size"::"public"."enum___pages_v_youtube_v_size";
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "posts_image_statement" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_posts_image_statement_text_size";
  CREATE TYPE "public"."enum_posts_image_statement_text_size" AS ENUM('default', 'small');
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum_posts_image_statement_text_size";
  ALTER TABLE "posts_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_posts_image_statement_text_size" USING "text_size"::"public"."enum_posts_image_statement_text_size";
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "posts_caption" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_posts_caption_size";
  CREATE TYPE "public"."enum_posts_caption_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_posts_caption_size";
  ALTER TABLE "posts_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_posts_caption_size" USING "size"::"public"."enum_posts_caption_size";
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "posts_youtube" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_posts_youtube_size";
  CREATE TYPE "public"."enum_posts_youtube_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_posts_youtube_size";
  ALTER TABLE "posts_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_posts_youtube_size" USING "size"::"public"."enum_posts_youtube_size";
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__posts_v_image_statement_v" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum___posts_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___posts_v_image_statement_v_text_size" AS ENUM('default', 'small');
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum___posts_v_image_statement_v_text_size";
  ALTER TABLE "__posts_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___posts_v_image_statement_v_text_size" USING "text_size"::"public"."enum___posts_v_image_statement_v_text_size";
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__posts_v_caption_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___posts_v_caption_v_size";
  CREATE TYPE "public"."enum___posts_v_caption_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___posts_v_caption_v_size";
  ALTER TABLE "__posts_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___posts_v_caption_v_size" USING "size"::"public"."enum___posts_v_caption_v_size";
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__posts_v_youtube_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___posts_v_youtube_v_size";
  CREATE TYPE "public"."enum___posts_v_youtube_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___posts_v_youtube_v_size";
  ALTER TABLE "__posts_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___posts_v_youtube_v_size" USING "size"::"public"."enum___posts_v_youtube_v_size";
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "works_image_statement" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum_works_image_statement_text_size";
  CREATE TYPE "public"."enum_works_image_statement_text_size" AS ENUM('default', 'small');
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum_works_image_statement_text_size";
  ALTER TABLE "works_image_statement" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum_works_image_statement_text_size" USING "text_size"::"public"."enum_works_image_statement_text_size";
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "works_caption" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_works_caption_size";
  CREATE TYPE "public"."enum_works_caption_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_works_caption_size";
  ALTER TABLE "works_caption" ALTER COLUMN "size" SET DATA TYPE "public"."enum_works_caption_size" USING "size"::"public"."enum_works_caption_size";
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "works_youtube" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum_works_youtube_size";
  CREATE TYPE "public"."enum_works_youtube_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum_works_youtube_size";
  ALTER TABLE "works_youtube" ALTER COLUMN "size" SET DATA TYPE "public"."enum_works_youtube_size" USING "size"::"public"."enum_works_youtube_size";
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE text;
  UPDATE "__works_v_image_statement_v" SET "text_size" = 'default' WHERE "text_size" = 'large';
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::text;
  DROP TYPE "public"."enum___works_v_image_statement_v_text_size";
  CREATE TYPE "public"."enum___works_v_image_statement_v_text_size" AS ENUM('default', 'small');
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DEFAULT 'default'::"public"."enum___works_v_image_statement_v_text_size";
  ALTER TABLE "__works_v_image_statement_v" ALTER COLUMN "text_size" SET DATA TYPE "public"."enum___works_v_image_statement_v_text_size" USING "text_size"::"public"."enum___works_v_image_statement_v_text_size";
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__works_v_caption_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___works_v_caption_v_size";
  CREATE TYPE "public"."enum___works_v_caption_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___works_v_caption_v_size";
  ALTER TABLE "__works_v_caption_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___works_v_caption_v_size" USING "size"::"public"."enum___works_v_caption_v_size";
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE text;
  UPDATE "__works_v_youtube_v" SET "size" = 'full' WHERE "size" = 'contained';
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::text;
  DROP TYPE "public"."enum___works_v_youtube_v_size";
  CREATE TYPE "public"."enum___works_v_youtube_v_size" AS ENUM('full', 'inset', 'small');
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DEFAULT 'full'::"public"."enum___works_v_youtube_v_size";
  ALTER TABLE "__works_v_youtube_v" ALTER COLUMN "size" SET DATA TYPE "public"."enum___works_v_youtube_v_size" USING "size"::"public"."enum___works_v_youtube_v_size";
  ALTER TABLE "pages_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum_pages_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum__pages_v_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "posts_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum_posts_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "_posts_v_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum__posts_v_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "works_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum_works_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "_works_v_blocks_feature_heading_offset" ADD COLUMN "body_size" "enum__works_v_blocks_feature_heading_offset_body_size" DEFAULT 'medium';
  ALTER TABLE "pages_transition" DROP COLUMN "text_size";
  UPDATE "pages_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "pages_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "pages_full_media" DROP COLUMN "text_size";
  ALTER TABLE "pages_media_split" DROP COLUMN "text_size";
  ALTER TABLE "pages_split_narrow" DROP COLUMN "text_size";
  ALTER TABLE "pages_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "pages_image_pair" DROP COLUMN "text_size";
  ALTER TABLE "pages_split_offset" DROP COLUMN "text_size";
  ALTER TABLE "pages_rich_text" DROP COLUMN "text_size";
  ALTER TABLE "pages_faq" DROP COLUMN "text_size";
  ALTER TABLE "pages_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "pages_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "pages_insight_list" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_transition_v" DROP COLUMN "text_size";
  UPDATE "_pages_v_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "_pages_v_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_full_media_v" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_media_split_v" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_split_narrow_v" DROP COLUMN "text_size";
  ALTER TABLE "_pages_v_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_image_pair_v" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_split_offset_v" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_rich_text_v" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_faq_v" DROP COLUMN "text_size";
  ALTER TABLE "_pages_v_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "_pages_v_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "__pages_v_insight_list_v" DROP COLUMN "text_size";
  ALTER TABLE "posts_transition" DROP COLUMN "text_size";
  UPDATE "posts_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "posts_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "posts_full_media" DROP COLUMN "text_size";
  ALTER TABLE "posts_media_split" DROP COLUMN "text_size";
  ALTER TABLE "posts_split_narrow" DROP COLUMN "text_size";
  ALTER TABLE "posts_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "posts_image_pair" DROP COLUMN "text_size";
  ALTER TABLE "posts_split_offset" DROP COLUMN "text_size";
  ALTER TABLE "posts_rich_text" DROP COLUMN "text_size";
  ALTER TABLE "posts_faq" DROP COLUMN "text_size";
  ALTER TABLE "posts_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "posts_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "posts_insight_list" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_transition_v" DROP COLUMN "text_size";
  UPDATE "_posts_v_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "_posts_v_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_full_media_v" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_media_split_v" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_split_narrow_v" DROP COLUMN "text_size";
  ALTER TABLE "_posts_v_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_image_pair_v" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_split_offset_v" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_rich_text_v" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_faq_v" DROP COLUMN "text_size";
  ALTER TABLE "_posts_v_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "_posts_v_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "__posts_v_insight_list_v" DROP COLUMN "text_size";
  ALTER TABLE "works_transition" DROP COLUMN "text_size";
  UPDATE "works_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "works_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "works_full_media" DROP COLUMN "text_size";
  ALTER TABLE "works_media_split" DROP COLUMN "text_size";
  ALTER TABLE "works_split_narrow" DROP COLUMN "text_size";
  ALTER TABLE "works_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "works_image_pair" DROP COLUMN "text_size";
  ALTER TABLE "works_split_offset" DROP COLUMN "text_size";
  ALTER TABLE "works_rich_text" DROP COLUMN "text_size";
  ALTER TABLE "works_faq" DROP COLUMN "text_size";
  ALTER TABLE "works_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "works_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "works_insight_list" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_transition_v" DROP COLUMN "text_size";
  UPDATE "_works_v_blocks_feature_heading_offset" SET "body_size" = 'large' WHERE "text_size" = 'large';
  ALTER TABLE "_works_v_blocks_feature_heading_offset" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_full_media_v" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_media_split_v" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_split_narrow_v" DROP COLUMN "text_size";
  ALTER TABLE "_works_v_blocks_carousel_split" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_image_pair_v" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_split_offset_v" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_rich_text_v" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_faq_v" DROP COLUMN "text_size";
  ALTER TABLE "_works_v_blocks_carousel_tabs" DROP COLUMN "text_size";
  ALTER TABLE "_works_v_blocks_feature_tabs" DROP COLUMN "text_size";
  ALTER TABLE "__works_v_insight_list_v" DROP COLUMN "text_size";
  DROP TYPE "public"."enum_pages_transition_text_size";
  DROP TYPE "public"."enum_pages_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum_pages_full_media_text_size";
  DROP TYPE "public"."enum_pages_media_split_text_size";
  DROP TYPE "public"."enum_pages_split_narrow_text_size";
  DROP TYPE "public"."enum_pages_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum_pages_image_pair_text_size";
  DROP TYPE "public"."enum_pages_split_offset_text_size";
  DROP TYPE "public"."enum_pages_rich_text_text_size";
  DROP TYPE "public"."enum_pages_faq_text_size";
  DROP TYPE "public"."enum_pages_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum_pages_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum_pages_insight_list_text_size";
  DROP TYPE "public"."enum___pages_v_transition_v_text_size";
  DROP TYPE "public"."enum__pages_v_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum___pages_v_full_media_v_text_size";
  DROP TYPE "public"."enum___pages_v_media_split_v_text_size";
  DROP TYPE "public"."enum___pages_v_split_narrow_v_text_size";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum___pages_v_image_pair_v_text_size";
  DROP TYPE "public"."enum___pages_v_split_offset_v_text_size";
  DROP TYPE "public"."enum___pages_v_rich_text_v_text_size";
  DROP TYPE "public"."enum___pages_v_faq_v_text_size";
  DROP TYPE "public"."enum__pages_v_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum__pages_v_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum___pages_v_insight_list_v_text_size";
  DROP TYPE "public"."enum_posts_transition_text_size";
  DROP TYPE "public"."enum_posts_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum_posts_full_media_text_size";
  DROP TYPE "public"."enum_posts_media_split_text_size";
  DROP TYPE "public"."enum_posts_split_narrow_text_size";
  DROP TYPE "public"."enum_posts_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum_posts_image_pair_text_size";
  DROP TYPE "public"."enum_posts_split_offset_text_size";
  DROP TYPE "public"."enum_posts_rich_text_text_size";
  DROP TYPE "public"."enum_posts_faq_text_size";
  DROP TYPE "public"."enum_posts_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum_posts_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum_posts_insight_list_text_size";
  DROP TYPE "public"."enum___posts_v_transition_v_text_size";
  DROP TYPE "public"."enum__posts_v_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum___posts_v_full_media_v_text_size";
  DROP TYPE "public"."enum___posts_v_media_split_v_text_size";
  DROP TYPE "public"."enum___posts_v_split_narrow_v_text_size";
  DROP TYPE "public"."enum__posts_v_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum___posts_v_image_pair_v_text_size";
  DROP TYPE "public"."enum___posts_v_split_offset_v_text_size";
  DROP TYPE "public"."enum___posts_v_rich_text_v_text_size";
  DROP TYPE "public"."enum___posts_v_faq_v_text_size";
  DROP TYPE "public"."enum__posts_v_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum__posts_v_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum___posts_v_insight_list_v_text_size";
  DROP TYPE "public"."enum_works_transition_text_size";
  DROP TYPE "public"."enum_works_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum_works_full_media_text_size";
  DROP TYPE "public"."enum_works_media_split_text_size";
  DROP TYPE "public"."enum_works_split_narrow_text_size";
  DROP TYPE "public"."enum_works_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum_works_image_pair_text_size";
  DROP TYPE "public"."enum_works_split_offset_text_size";
  DROP TYPE "public"."enum_works_rich_text_text_size";
  DROP TYPE "public"."enum_works_faq_text_size";
  DROP TYPE "public"."enum_works_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum_works_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum_works_insight_list_text_size";
  DROP TYPE "public"."enum___works_v_transition_v_text_size";
  DROP TYPE "public"."enum__works_v_blocks_feature_heading_offset_text_size";
  DROP TYPE "public"."enum___works_v_full_media_v_text_size";
  DROP TYPE "public"."enum___works_v_media_split_v_text_size";
  DROP TYPE "public"."enum___works_v_split_narrow_v_text_size";
  DROP TYPE "public"."enum__works_v_blocks_carousel_split_text_size";
  DROP TYPE "public"."enum___works_v_image_pair_v_text_size";
  DROP TYPE "public"."enum___works_v_split_offset_v_text_size";
  DROP TYPE "public"."enum___works_v_rich_text_v_text_size";
  DROP TYPE "public"."enum___works_v_faq_v_text_size";
  DROP TYPE "public"."enum__works_v_blocks_carousel_tabs_text_size";
  DROP TYPE "public"."enum__works_v_blocks_feature_tabs_text_size";
  DROP TYPE "public"."enum___works_v_insight_list_v_text_size";`)
}
