/**
 * Bakes the liquid glass's environment (src/components/SiteChrome/liquid-glass/
 * studio-env.ts) from the HDR the Codrops demo reflects: drei's "studio"
 * preset, Poly Haven's "Studio Small 03" (CC0), at the drei-assets commit the
 * demo pins. The 1024×512 equirect is area-averaged in linear light down to
 * 64×32 and stored as RGBE, so the glass can sample it without loading an HDR.
 *
 *   pnpm tsx scripts/bake-glass-env.ts
 */
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const SOURCE =
  'https://raw.githack.com/pmndrs/drei-assets/456060a26bbeb8fdf79326f224b6d99b8bcce736/hdri/studio_small_03_1k.hdr'
const OUT = resolve(import.meta.dirname, '../src/components/SiteChrome/liquid-glass/studio-env.ts')
const WIDTH = 64
const HEIGHT = 32

/** Decodes a Radiance .hdr (new-style RLE or flat RGBE) to linear RGB floats. */
function decodeHdr(bytes: Uint8Array) {
  let offset = 0
  const line = () => {
    let text = ''
    while (bytes[offset] !== 0x0a) text += String.fromCharCode(bytes[offset++])
    offset++
    return text
  }
  let header = line()
  while (header !== '') header = line()
  const size = /-Y (\d+) \+X (\d+)/.exec(line())
  if (!size) throw new Error('Unsupported HDR orientation')
  const height = Number(size[1])
  const width = Number(size[2])
  const rgbe = new Uint8Array(width * height * 4)
  const scanline = new Uint8Array(width * 4)

  for (let row = 0; row < height; row++) {
    if (bytes[offset] === 2 && bytes[offset + 1] === 2 && (bytes[offset + 2] & 0x80) === 0) {
      offset += 4
      for (let channel = 0; channel < 4; channel++) {
        let column = 0
        while (column < width) {
          let count = bytes[offset++]
          if (count > 128) {
            count -= 128
            const value = bytes[offset++]
            while (count--) scanline[column++ * 4 + channel] = value
          } else {
            while (count--) scanline[column++ * 4 + channel] = bytes[offset++]
          }
        }
      }
    } else {
      scanline.set(bytes.subarray(offset, offset + width * 4))
      offset += width * 4
    }
    rgbe.set(scanline, row * width * 4)
  }

  const rgb = new Float32Array(width * height * 3)
  for (let i = 0; i < width * height; i++) {
    const exponent = rgbe[i * 4 + 3]
    const scale = exponent ? 2 ** (exponent - 136) : 0
    rgb[i * 3] = rgbe[i * 4] * scale
    rgb[i * 3 + 1] = rgbe[i * 4 + 1] * scale
    rgb[i * 3 + 2] = rgbe[i * 4 + 2] * scale
  }
  return { width, height, rgb }
}

/** Area average of the equirect down to WIDTH × HEIGHT, in linear light. */
function downsample({ width, height, rgb }: ReturnType<typeof decodeHdr>) {
  const out = new Float32Array(WIDTH * HEIGHT * 3)
  const stepX = width / WIDTH
  const stepY = height / HEIGHT
  for (let y = 0; y < HEIGHT; y++) {
    for (let x = 0; x < WIDTH; x++) {
      const sum = [0, 0, 0]
      for (let sy = 0; sy < stepY; sy++) {
        for (let sx = 0; sx < stepX; sx++) {
          const i = ((y * stepY + sy) * width + x * stepX + sx) * 3
          sum[0] += rgb[i]
          sum[1] += rgb[i + 1]
          sum[2] += rgb[i + 2]
        }
      }
      const o = (y * WIDTH + x) * 3
      for (let c = 0; c < 3; c++) out[o + c] = sum[c] / (stepX * stepY)
    }
  }
  return out
}

/** Linear RGB to RGBE bytes. */
function encodeRgbe(rgb: Float32Array) {
  const out = new Uint8Array((rgb.length / 3) * 4)
  for (let i = 0; i < rgb.length / 3; i++) {
    const max = Math.max(rgb[i * 3], rgb[i * 3 + 1], rgb[i * 3 + 2])
    if (max < 1e-32) continue
    const exponent = Math.ceil(Math.log2(max))
    const scale = 256 / 2 ** exponent
    out[i * 4] = Math.min(255, Math.floor(rgb[i * 3] * scale))
    out[i * 4 + 1] = Math.min(255, Math.floor(rgb[i * 3 + 1] * scale))
    out[i * 4 + 2] = Math.min(255, Math.floor(rgb[i * 3 + 2] * scale))
    out[i * 4 + 3] = exponent + 128
  }
  return out
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`Could not fetch ${SOURCE}: ${response.status}`)
const baked = encodeRgbe(downsample(decodeHdr(new Uint8Array(await response.arrayBuffer()))))

writeFileSync(
  OUT,
  `// Generated by scripts/bake-glass-env.ts. Do not edit.
// drei "studio" preset: Poly Haven "Studio Small 03" (CC0), ${WIDTH}×${HEIGHT} equirect, RGBE.

export const STUDIO_ENV = {
  width: ${WIDTH},
  height: ${HEIGHT},
  rgbe: '${Buffer.from(baked).toString('base64')}',
}
`,
)
console.log(`Wrote ${OUT}`)
